version: '3.3'

services:
    #web:
    neo4j:
        image: neo4j:latest
        #stdin_open: true
        #tty: true
        # user: root
        environment:
            NEO4J_AUTH: none
            NEO4J_dbms_default__listen__address: 0.0.0.0
        volumes:
            #- graph_conf:/conf
            - graph_data:/data
            #- graph_import:/import
            #- graph_logs:/logs
            #- graph_metrics:/metrics
            #- graph_plugins:/plugins
            #- graph_ssl:/ssl
        ports:
            - '7473:7473'
            - '7474:7474'
            - '7687:7687'
        networks:
            - backend
    api:
        build: ./api/
        depends_on:
            - neo4j
        ports:
            - '3000:3000'
            - '9229:9229'
        volumes:
            - ./api:/usr/src/app
        networks:
            - backend
            - frontend
        command: ["npm", "run", "dev"]

volumes: 
    graph_conf:
    graph_data:
    graph_import:
    graph_logs:
    graph_metrics:
    graph_plugins:
    graph_ssl:

networks:
    backend:
    frontend: